# Generated by Django 5.2.8 on 2025-11-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(choices=[('Sellado', 'Sellado de Cerámico'), ('Pulido', 'Pulido Profesional'), ('Pintura', 'Pintura de Carrocería'), ('Desabolladura', 'Desabolladura'), ('Lavado', 'Lavado Completo'), ('RestauracionFocos', 'Restauración de Focos'), ('LavadoMotor', 'Lavado de Motor'), ('Sanitizado', 'Sanitizado con Ozono'), ('Tapiceria', 'Lavado de Tapiz')], max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
    ]
